### PR TITLE
♻️ import DEFAULT_PRIME value

### PR DESCRIPTION
**Pull request by qd-qd**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/103)

### CODE REVIEW

**Comment by qd-qd** [comment]
@liorgold2 This PR takes into account the comments you left to me on PR #97. It is ready to be merged

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/103)* status: all files reviewed, 1 unresolved discussion (waiting on @qd-qd)

___
*[`src/starkware/crypto/signature/nothing_up_my_sleeve_gen.py` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo-lang/103#-NCkyT43Cki63NrPz3YZ:-NCkyT441FFvcvqW_VOA:b-iluukf) ([raw file](https://github.com/starkware-libs/cairo-lang/blob/95c89ee7e874c4ae8e8f9edca0a1b50d471f5810/src/starkware/crypto/signature/nothing_up_my_sleeve_gen.py#L52)):*
> ```Python
> def generate_constant_points(n_points):
>     """
>     Generates points from the curve y^2 = x^3 + x + beta over GF(DEFAULT_PRIME) where beta and the
> ```

Revert changes to this file.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/103)* status: all files reviewed, 2 unresolved discussions (waiting on @qd-qd)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo-lang/103#-NCkyWbr0Xti7xoZm6Be:-NCkyWbr0Xti7xoZm6Bf:b-dbwpnn) (no related file):*
Please run `docker build .` to run the tests. We haven't set a CI on this repo.

___

**Review by liorgold2 — COMMENTED** [review]
Can you try running `build.sh`, and then go to `build/Release` and run `make all` and `ctest`?

I ran the tests, and there seems to be an import problem:

```
4:     return _bootstrap._gcd_import(name[level:], package, level)
4: src/starkware/cairo/lang/builtins/range_check/cairo_run_builtins_range_check_test_venv-site/starkware/cairo/lang/builtins/range_check/range_check_builtin_runner_test.py:3: in <module>
4:     from starkware.cairo.lang.builtins.builtin_runner_test_utils import PRIME, compile_and_run
4: E   ImportError: cannot import name 'PRIME' from 'starkware.cairo.lang.builtins.builtin_runner_test_utils' (/app/build/Release/src/starkware/cairo/lang/builtins/range_check/cairo_run_builtins_range_check_test_venv-site/starkware/cairo/lang/builtins/builtin_runner_test_utils.py)
```

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/103#-:-NCzLCcy1eIt5hiXwUYn:b9hzmbp)* status: all files reviewed, 1 unresolved discussion (waiting on @qd-qd)

**Pull request closed without merging**
